const collocationData = [
    // ==========================================
    // 1. EDUCATION & LEARNING (30)
    // ==========================================
    { verb: "Gain", noun: "valuable experience" },
    { verb: "Acquire", noun: "new knowledge" },
    { verb: "Meet", noun: "a strict deadline" },
    { verb: "Achieve", noun: "a specific goal" },
    { verb: "Attend", noun: "a university lecture" },
    { verb: "Develop", noun: "practical skills" },
    { verb: "Overcome", noun: "a difficult obstacle" },
    { verb: "Fulfill", noun: "your true potential" },
    { verb: "Face", noun: "a major challenge" },
    { verb: "Make", noun: "steady progress" },
    { verb: "Conduct", noun: "scientific research" },
    { verb: "Submit", noun: "an academic assignment" },
    { verb: "Pass", noun: "a final exam" },
    { verb: "Memorize", noun: "historical facts" },
    { verb: "Enhance", noun: "cognitive development" },
    { verb: "Broaden", noun: "your horizons" },
    { verb: "Encourage", noun: "independent thinking" },
    { verb: "Provide", noun: "equal opportunities" },
    { verb: "Enroll", noun: "in a degree program" },
    { verb: "Skip", noun: "a scheduled class" },
    { verb: "Review", noun: "study materials" },
    { verb: "Stimulate", noun: "creative thinking" },
    { verb: "Foster", noun: "a learning environment" },
    { verb: "Tailor", noun: "the curriculum" },
    { verb: "Assess", noun: "student performance" },
    { verb: "Boost", noun: "academic achievement" },
    { verb: "Master", noun: "a foreign language" },
    { verb: "Join", noun: "an extracurricular activity" },
    { verb: "Award", noun: "a financial scholarship" },
    { verb: "Pursue", noun: "higher education" },

    // ==========================================
    // 2. ENVIRONMENT & NATURE (30)
    // ==========================================
    { verb: "Protect", noun: "the natural environment" },
    { verb: "Reduce", noun: "carbon emissions" },
    { verb: "Destroy", noun: "wildlife habitats" },
    { verb: "Conserve", noun: "energy resources" },
    { verb: "Tackle", noun: "climate change" },
    { verb: "Prevent", noun: "severe pollution" },
    { verb: "Preserve", noun: "endangered species" },
    { verb: "Generate", noun: "renewable electricity" },
    { verb: "Damage", noun: "fragile ecosystems" },
    { verb: "Promote", noun: "sustainable development" },
    { verb: "Plant", noun: "native trees" },
    { verb: "Recycle", noun: "household waste" },
    { verb: "Threaten", noun: "marine life" },
    { verb: "Deplete", noun: "natural resources" },
    { verb: "Contaminate", noun: "drinking water" },
    { verb: "Clear", noun: "ancient forests" },
    { verb: "Poach", noun: "wild animals" },
    { verb: "Ban", noun: "single-use plastics" },
    { verb: "Combat", noun: "global warming" },
    { verb: "Introduce", noun: "green policies" },
    { verb: "Emit", noun: "toxic gases" },
    { verb: "Install", noun: "solar panels" },
    { verb: "Dispose", noun: "of toxic waste" },
    { verb: "Harm", noun: "the ozone layer" },
    { verb: "Shift", noun: "to clean energy" },
    { verb: "Melt", noun: "the polar ice caps" },
    { verb: "Experience", noun: "extreme weather" },
    { verb: "Enforce", noun: "strict environmental laws" },
    { verb: "Raise", noun: "ecological awareness" },
    { verb: "Restore", noun: "damaged landscapes" },

    // ==========================================
    // 3. HEALTH & LIFESTYLE (30)
    // ==========================================
    { verb: "Maintain", noun: "a healthy lifestyle" },
    { verb: "Prevent", noun: "chronic diseases" },
    { verb: "Improve", noun: "physical fitness" },
    { verb: "Cause", noun: "severe illness" },
    { verb: "Suffer", noun: "from extreme stress" },
    { verb: "Adopt", noun: "a balanced diet" },
    { verb: "Cure", noun: "a viral infection" },
    { verb: "Provide", noun: "medical treatment" },
    { verb: "Reduce", noun: "childhood obesity" },
    { verb: "Experience", noun: "mental fatigue" },
    { verb: "Relieve", noun: "muscle tension" },
    { verb: "Quit", noun: "a bad habit" },
    { verb: "Burn", noun: "excess calories" },
    { verb: "Prescribe", noun: "strong medication" },
    { verb: "Diagnose", noun: "a rare condition" },
    { verb: "Undergo", noun: "major surgery" },
    { verb: "Recover", noun: "from an injury" },
    { verb: "Catch", noun: "the seasonal flu" },
    { verb: "Boost", noun: "the immune system" },
    { verb: "Consume", noun: "processed foods" },
    { verb: "Digest", noun: "heavy meals" },
    { verb: "Lower", noun: "blood pressure" },
    { verb: "Build", noun: "muscle strength" },
    { verb: "Avoid", noun: "sedentary behavior" },
    { verb: "Promote", noun: "public health" },
    { verb: "Fund", noun: "hospital facilities" },
    { verb: "Limit", noun: "sugar intake" },
    { verb: "Ensure", noun: "adequate sleep" },
    { verb: "Trigger", noun: "an allergic reaction" },
    { verb: "Manage", noun: "chronic pain" },

    // ==========================================
    // 4. SOCIETY & GOVERNMENT (30)
    // ==========================================
    { verb: "Implement", noun: "a new policy" },
    { verb: "Provide", noun: "financial support" },
    { verb: "Solve", noun: "a complex issue" },
    { verb: "Take", noun: "full responsibility" },
    { verb: "Make", noun: "a significant impact" },
    { verb: "Express", noun: "a strong opinion" },
    { verb: "Draw", noun: "a logical conclusion" },
    { verb: "Break", noun: "the traditional rules" },
    { verb: "Address", noun: "the root cause" },
    { verb: "Introduce", noun: "strict legislation" },
    { verb: "Allocate", noun: "public funding" },
    { verb: "Spark", noun: "a fierce debate" },
    { verb: "Bridge", noun: "the wealth gap" },
    { verb: "Support", noun: "vulnerable communities" },
    { verb: "Demand", noun: "equal rights" },
    { verb: "Protest", noun: "against unfair laws" },
    { verb: "Face", noun: "public backlash" },
    { verb: "Ensure", noun: "social stability" },
    { verb: "Improve", noun: "living standards" },
    { verb: "Eradicate", noun: "extreme poverty" },
    { verb: "Provide", noun: "basic necessities" },
    { verb: "Tackle", noun: "homelessness" },
    { verb: "Hold", noun: "a democratic election" },
    { verb: "Represent", noun: "the local citizens" },
    { verb: "Pay", noun: "income tax" },
    { verb: "Respect", noun: "cultural diversity" },
    { verb: "Challenge", noun: "the status quo" },
    { verb: "Create", noun: "a sense of community" },
    { verb: "Govern", noun: "a large population" },
    { verb: "Maintain", noun: "public order" },

    // ==========================================
    // 5. WORK & BUSINESS (30)
    // ==========================================
    { verb: "Pursue", noun: "a successful career" },
    { verb: "Boost", noun: "worker productivity" },
    { verb: "Create", noun: "employment opportunities" },
    { verb: "Hire", noun: "qualified staff" },
    { verb: "Fire", noun: "incompetent employees" },
    { verb: "Earn", noun: "a competitive salary" },
    { verb: "Launch", noun: "a marketing campaign" },
    { verb: "Target", noun: "a specific audience" },
    { verb: "Maximize", noun: "corporate profits" },
    { verb: "Suffer", noun: "heavy financial losses" },
    { verb: "Expand", noun: "the business overseas" },
    { verb: "Sign", noun: "a binding contract" },
    { verb: "Negotiate", noun: "a better deal" },
    { verb: "Provide", noun: "excellent customer service" },
    { verb: "Meet", noun: "consumer demand" },
    { verb: "Outsource", noun: "cheap labor" },
    { verb: "Retire", noun: "from the workforce" },
    { verb: "Resign", noun: "from a stressful job" },
    { verb: "Promote", noun: "a junior manager" },
    { verb: "Establish", noun: "a new company" },
    { verb: "Dominate", noun: "the global market" },
    { verb: "Invest", noun: "in employee training" },
    { verb: "Balance", noun: "work and life" },
    { verb: "Commute", noun: "to the office" },
    { verb: "Work", noun: "flexible hours" },
    { verb: "Manage", noun: "a team of experts" },
    { verb: "Achieve", noun: "commercial success" },
    { verb: "Develop", noun: "leadership skills" },
    { verb: "Build", noun: "a professional network" },
    { verb: "Face", noun: "stiff competition" },

    // ==========================================
    // 6. TECHNOLOGY & MEDIA (30)
    // ==========================================
    { verb: "Embrace", noun: "new technology" },
    { verb: "Access", noun: "the internet" },
    { verb: "Protect", noun: "data privacy" },
    { verb: "Browse", noun: "social media" },
    { verb: "Download", noun: "digital files" },
    { verb: "Replace", noun: "human workers" },
    { verb: "Develop", noun: "artificial intelligence" },
    { verb: "Upgrade", noun: "computer software" },
    { verb: "Install", noun: "a mobile application" },
    { verb: "Invent", noun: "a modern device" },
    { verb: "Rely", noun: "on smartphones" },
    { verb: "Spread", noun: "fake news" },
    { verb: "Publish", noun: "an online article" },
    { verb: "Stream", noun: "high-definition video" },
    { verb: "Store", noun: "data in the cloud" },
    { verb: "Automate", noun: "manual tasks" },
    { verb: "Hack", noun: "a secure system" },
    { verb: "Launch", noun: "a satellite" },
    { verb: "Share", noun: "personal information" },
    { verb: "Censor", noun: "inappropriate content" },
    { verb: "Communicate", noun: "via text message" },
    { verb: "Influence", noun: "public opinion" },
    { verb: "Attract", noun: "a massive audience" },
    { verb: "Broadcast", noun: "a live event" },
    { verb: "Monitor", noun: "screen time" },
    { verb: "Limit", noun: "device usage" },
    { verb: "Connect", noun: "with people globally" },
    { verb: "Revolutionize", noun: "the digital landscape" },
    { verb: "Navigate", noun: "a complex website" },
    { verb: "Program", noun: "a complex algorithm" },

    // ==========================================
    // 7. CRIME & JUSTICE (30)
    // ==========================================
    { verb: "Commit", noun: "a serious crime" },
    { verb: "Break", noun: "the strict law" },
    { verb: "Arrest", noun: "a violent suspect" },
    { verb: "Investigate", noun: "a murder case" },
    { verb: "Gather", noun: "physical evidence" },
    { verb: "Charge", noun: "the defendant" },
    { verb: "Defend", noun: "the accused person" },
    { verb: "Sentence", noun: "a guilty criminal" },
    { verb: "Serve", noun: "time in prison" },
    { verb: "Release", noun: "an inmate" },
    { verb: "Rehabilitate", noun: "young offenders" },
    { verb: "Deter", noun: "criminal behavior" },
    { verb: "Enforce", noun: "harsh punishments" },
    { verb: "Prevent", noun: "juvenile delinquency" },
    { verb: "Patrol", noun: "the city streets" },
    { verb: "Report", noun: "a stolen vehicle" },
    { verb: "Witness", noun: "an armed robbery" },
    { verb: "Smuggle", noun: "illegal goods" },
    { verb: "Hack", noun: "bank accounts" },
    { verb: "Protect", noun: "innocent victims" },
    { verb: "Testify", noun: "in a courtroom" },
    { verb: "Abolish", noun: "the death penalty" },
    { verb: "Reduce", noun: "the crime rate" },
    { verb: "Install", noun: "security cameras" },
    { verb: "Punish", noun: "illegal behavior" },
    { verb: "Obey", noun: "traffic regulations" },
    { verb: "Fine", noun: "a speeding driver" },
    { verb: "Combat", noun: "international terrorism" },
    { verb: "Maintain", noun: "strict security" },
    { verb: "Violate", noun: "human rights" },

    // ==========================================
    // 8. TOURISM & CULTURE (30)
    // ==========================================
    { verb: "Attract", noun: "international tourists" },
    { verb: "Boost", noun: "the local economy" },
    { verb: "Experience", noun: "a different culture" },
    { verb: "Preserve", noun: "historical monuments" },
    { verb: "Damage", noun: "ancient ruins" },
    { verb: "Book", noun: "a cheap flight" },
    { verb: "Explore", noun: "a remote destination" },
    { verb: "Respect", noun: "local traditions" },
    { verb: "Sample", noun: "traditional cuisine" },
    { verb: "Speak", noun: "a foreign language" },
    { verb: "Immerse", noun: "yourself in history" },
    { verb: "Celebrate", noun: "a cultural festival" },
    { verb: "Wear", noun: "traditional clothing" },
    { verb: "Generate", noun: "tourism revenue" },
    { verb: "Provide", noun: "hospitality services" },
    { verb: "Overcrowd", noun: "popular beaches" },
    { verb: "Erode", noun: "national identity" },
    { verb: "Promote", noun: "domestic travel" },
    { verb: "Construct", noun: "luxury hotels" },
    { verb: "Visit", noun: "an art exhibition" },
    { verb: "Display", noun: "ancient artifacts" },
    { verb: "Appreciate", noun: "classical music" },
    { verb: "Perform", noun: "a live concert" },
    { verb: "Translate", noun: "the local dialect" },
    { verb: "Adapt", noun: "to foreign customs" },
    { verb: "Suffer", noun: "from culture shock" },
    { verb: "Buy", noun: "handmade souvenirs" },
    { verb: "Guide", noun: "a group tour" },
    { verb: "Limit", noun: "visitor numbers" },
    { verb: "Protect", noun: "cultural heritage" },

    // ==========================================
    // 9. ECONOMY & MONEY (30)
    // ==========================================
    { verb: "Invest", noun: "taxpayer money" },
    { verb: "Generate", noun: "massive profits" },
    { verb: "Suffer", noun: "an economic crisis" },
    { verb: "Pay", noun: "high taxes" },
    { verb: "Manage", noun: "a tight budget" },
    { verb: "Save", noun: "money for retirement" },
    { verb: "Borrow", noun: "a large loan" },
    { verb: "Repay", noun: "personal debt" },
    { verb: "Charge", noun: "high interest rates" },
    { verb: "Open", noun: "a savings account" },
    { verb: "Transfer", noun: "funds internationally" },
    { verb: "Subsidize", noun: "local agriculture" },
    { verb: "Import", noun: "foreign goods" },
    { verb: "Export", noun: "domestic products" },
    { verb: "Control", noun: "rapid inflation" },
    { verb: "Stimulate", noun: "consumer spending" },
    { verb: "Reduce", noun: "living costs" },
    { verb: "Afford", noun: "basic housing" },
    { verb: "Increase", noun: "the minimum wage" },
    { verb: "Donate", noun: "to a charity" },
    { verb: "Fund", noun: "public services" },
    { verb: "Declare", noun: "corporate bankruptcy" },
    { verb: "Maximize", noun: "financial returns" },
    { verb: "Analyze", noun: "market trends" },
    { verb: "Monopolize", noun: "the global market" },
    { verb: "Compete", noun: "on price" },
    { verb: "Establish", noun: "a free-trade zone" },
    { verb: "Levy", noun: "a heavy fine" },
    { verb: "Inherit", noun: "family wealth" },
    { verb: "Waste", noun: "financial resources" },

    // ==========================================
    // 10. FAMILY & RELATIONSHIPS (30)
    // ==========================================
    { verb: "Raise", noun: "young children" },
    { verb: "Support", noun: "your family" },
    { verb: "Spend", noun: "quality time" },
    { verb: "Build", noun: "a strong relationship" },
    { verb: "Instill", noun: "good values" },
    { verb: "Set", noun: "strict boundaries" },
    { verb: "Discipline", noun: "bad behavior" },
    { verb: "Praise", noun: "good behavior" },
    { verb: "Provide", noun: "emotional support" },
    { verb: "Share", noun: "household chores" },
    { verb: "Look", noun: "after elderly parents" },
    { verb: "Maintain", noun: "family traditions" },
    { verb: "Influence", noun: "childhood development" },
    { verb: "Resolve", noun: "a fierce argument" },
    { verb: "Apologize", noun: "for a mistake" },
    { verb: "Forgive", noun: "a close friend" },
    { verb: "Form", noun: "a deep bond" },
    { verb: "Respect", noun: "older generations" },
    { verb: "Spoil", noun: "a young child" },
    { verb: "Neglect", noun: "parental duties" },
    { verb: "Balance", noun: "work and family" },
    { verb: "Adopt", noun: "an orphaned child" },
    { verb: "Attend", noun: "a family gathering" },
    { verb: "Pass", noun: "down inherited traits" },
    { verb: "Communicate", noun: "openly with partners" },
    { verb: "Divorce", noun: "an unhappy spouse" },
    { verb: "Marry", noun: "a supportive partner" },
    { verb: "Celebrate", noun: "a wedding anniversary" },
    { verb: "Mourn", noun: "a tragic loss" },
    { verb: "Cherish", noun: "childhood memories" }
];